name: "FEATURE"
description: 작업 사항을 작성해주세요.
title: "[FEATURE] "
body:
  - type: markdown
    attributes:
      value: |
        작성 예시 : "[ FEATURE ] 회원가입 API 구현"
  - type: textarea
    id: feat-description
    attributes:
      label: 🛠 기능 설명
      description: 어떠한 작업을 수행하셨는지 작성해주세요.
      placeholder: 설명을 작성해주세요.
    validations:
      required: true
  - type: textarea
    id: feat-list
    attributes:
      label: 📝 상세 기능
      description: 기능에 필요한 목록을 작성해주세요.
      placeholder: 목록을 작성해주세요.
    validations:
      required: false
  - type: textarea
    id: reproduction
    attributes:
      label: 🔍 접근 방법
      description: 고려하신 방법이나, 접근에 대해서 설명해주세요.
      placeholder: 설명을 작성해주세요.
    validations:
      required: false
